[package]
name = "stu"
version = "0.5.2"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

exclude = ["/.github", "/img", "/tool", "go.work*", "Makefile", "_config.yml"]

[dependencies]
ansi-to-tui = "6.0.0"
anyhow = "1.0.87"
arboard = "3.4.0"
aws-config = "1.5.5"
aws-sdk-s3 = "1.48.0"
aws-smithy-types = "1.2.4"
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
dirs = "5.0.1"
humansize = "2.1.3"
image = "0.25.2"
infer = "0.16.0"
itertools = "0.13.0"
itsuki = "0.2.0"
once_cell = "1.19.0"
open = "5.3.0"
ratatui = { version = "0.28.1", features = ["unstable-widget-ref"] }
ratatui-image = "1.0.5"
serde = { version = "1.0.210", features = ["derive"] }
syntect = { version = "5.2.0", default-features = false, features = [
    "default-fancy",
] }
textwrap = "0.16.1"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tui-input = "0.10.1"

[dev-dependencies]
rstest = "0.22.0"

[features]
imggen = [] # for test
