[package]
name = "stu"
version = "0.4.2"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arboard = "3.4.0"
aws-config = "1.4.0"
aws-sdk-s3 = "1.29.0"
aws-smithy-types = "1.1.9"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.27.0"
dirs = "5.0.1"
humansize = "2.1.3"
itertools = "0.13.0"
itsuki = "0.2.0"
open = "5.1.3"
ratatui = { version = "0.26.2", features = [
    "all-widgets",
    "unstable-widget-ref",
] }
serde = "1.0.202"
serde_derive = "1.0.202"
textwrap = "0.16.1"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tui-input = "0.8.0"

[dev-dependencies]
indoc = "2.0.5"   # https://github.com/ratatui-org/ratatui/issues/1043
rstest = "0.19.0"

[features]
imggen = [] # for test
