[package]
name = "stu"
version = "0.4.1"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
arboard = "3.3.2"
aws-config = "1.1.9"
aws-sdk-s3 = "1.21.0"
aws-smithy-types = "1.1.8"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.27.0"
dirs = "5.0.1"
enum-tag = "0.3.0"
humansize = "2.1.3"
itertools = "0.12.1"
open = "5.1.2"
ratatui = { version = "0.26.1", features = ["all-widgets"] }
serde = "1.0.197"
serde_derive = "1.0.197"
textwrap = "0.16.1"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
maplit = "1.0.2"
rstest = "0.18.2"

[features]
imggen = [] # for test
