[package]
name = "stu"
version = "0.3.0"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
arboard = "3.3.2"
aws-config = "1.1.7"
aws-sdk-s3 = "1.17.0"
aws-smithy-types = "1.1.7"
chrono = "0.4.35"
clap = { version = "4.5.2", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.27.0"
dirs = "5.0.1"
enum-tag = "0.3.0"
humansize = "2.1.3"
open = "5.1.1"
ratatui = { version = "0.26.1", features = ["all-widgets"] }
serde = "1.0.153"
serde_derive = "1.0.153"
textwrap = "0.16.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
maplit = "1.0.2"
rstest = "0.18.2"
