[package]
name = "stu"
version = "0.2.5"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
aws-config = "1.0.1"
aws-sdk-s3 = "1.4.0"
aws-smithy-types = "1.0.1"
chrono = "0.4.23"
clap = { version = "4.1.6", features = ["derive"] }
confy = "0.6.0"
crossterm = "0.27.0"
dirs = "5.0.1"
humansize = "2.1.3"
open = "5.0.0"
ratatui = { version = "0.26.1", features = ["all-widgets"] }
serde = "1.0.153"
serde_derive = "1.0.153"
tokio = { version = "1", features = ["full"] }
