[package]
name = "stu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws-smithy-types = "0.54.3"
chrono = "0.4.23"
clap = { version = "4.1.6", features = ["derive"] }
crossterm = "0.26.0"
humansize = "2.1.3"
tokio = { version = "1", features = ["full"] }
tui = "0.19.0"
