[package]
name = "stu"
version = "0.1.0"
description = "TUI application for AWS S3 written in Rust using tui-rs"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws-smithy-types = "0.54.3"
chrono = "0.4.23"
clap = { version = "4.1.6", features = ["derive"] }
crossterm = "0.26.0"
humansize = "2.1.3"
open = "3.2.0"
tokio = { version = "1", features = ["full"] }
tui = "0.19.0"
