[package]
name = "stu"
version = "0.5.0"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"

exclude = ["/.github", "/img", "/tool", "go.work*", "Makefile", "_config.yml"]

[dependencies]
ansi-to-tui = "4.0.1"
anyhow = "1.0.86"
arboard = "3.4.0"
aws-config = "1.5.1"
aws-sdk-s3 = "1.36.0"
aws-smithy-types = "1.2.0"
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
confy = "0.6.1"
crossterm = "0.27.0"
dirs = "5.0.1"
humansize = "2.1.3"
itertools = "0.13.0"
itsuki = "0.2.0"
once_cell = "1.19.0"
open = "5.1.4"
ratatui = { version = "0.26.3", features = ["unstable-widget-ref"] }
serde = { version = "1.0.203", features = ["derive"] }
syntect = { version = "5.2.0", default-features = false, features = [
    "default-fancy",
] }
textwrap = "0.16.1"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tui-input = "0.8.0"

[dev-dependencies]
rstest = "0.21.0"

[features]
imggen = [] # for test
